# Seyed Mohammad Amin Atyabi - 830402014

## NumPy

### 1

**1**

In [23]:
import random

vector = [ random.randint(10, 1000) for x in range(0, 1000) ]
vector

[809,
 513,
 791,
 405,
 13,
 371,
 50,
 51,
 617,
 982,
 149,
 648,
 554,
 813,
 972,
 928,
 904,
 567,
 668,
 285,
 642,
 697,
 377,
 22,
 982,
 980,
 929,
 613,
 491,
 57,
 979,
 163,
 997,
 942,
 737,
 80,
 389,
 528,
 746,
 98,
 537,
 86,
 28,
 737,
 180,
 760,
 254,
 246,
 104,
 12,
 552,
 244,
 205,
 449,
 724,
 452,
 678,
 597,
 276,
 232,
 578,
 275,
 938,
 860,
 921,
 273,
 575,
 663,
 897,
 683,
 366,
 259,
 298,
 936,
 200,
 753,
 402,
 430,
 896,
 536,
 417,
 839,
 729,
 81,
 405,
 957,
 763,
 37,
 215,
 581,
 784,
 158,
 693,
 89,
 134,
 118,
 767,
 306,
 19,
 753,
 236,
 370,
 578,
 681,
 485,
 783,
 168,
 63,
 688,
 733,
 631,
 544,
 481,
 660,
 706,
 591,
 189,
 624,
 91,
 69,
 67,
 919,
 757,
 827,
 834,
 425,
 862,
 258,
 597,
 628,
 830,
 197,
 961,
 441,
 375,
 979,
 763,
 400,
 34,
 710,
 76,
 602,
 539,
 423,
 556,
 545,
 873,
 667,
 599,
 972,
 437,
 420,
 251,
 121,
 779,
 778,
 453,
 952,
 286,
 23,
 565,
 807,
 94,
 82,
 934,
 994,
 504,
 650,
 595,
 900,
 22

**2**

In [24]:
_sum_ = sum(vector)
count = len(vector)
mean = _sum_ / count
variance = (sum(map(lambda x: (x - mean) ** 2, vector))) / (count - 1)
print(f'Average = {mean}')
print(f'Variance = {variance}')

Average = 513.911
Variance = 83545.63471371365


### 2

**1**

In [25]:
matrix = [ [random.random() for j in range(0, 10)] for i in range(0, 10) ]
matrix

[[0.47471542768100694,
  0.6197166963584445,
  0.5723218464572929,
  0.3769329248881155,
  0.11727562061267338,
  0.6845893839028628,
  0.14543806720106423,
  0.2829613684090616,
  0.22795040112700438,
  0.4929098611717091],
 [0.23136955715547303,
  0.6208659073165431,
  0.8003359876435977,
  0.1332134867339293,
  0.30963758799794294,
  0.8693962654758759,
  0.5399922004919874,
  0.8636412726063717,
  0.4716530543783608,
  0.16417402252396052],
 [0.6192822791420106,
  0.6946326774250582,
  0.5384241037002085,
  0.4942272937924128,
  0.8476111382609233,
  0.23843614600496976,
  0.26715238090335325,
  0.9637887191423444,
  0.35068888425448785,
  0.7691205747060654],
 [0.9570291764210689,
  0.161709101266598,
  0.1733344075417188,
  0.05135078281836747,
  0.177744670651379,
  0.06614188426969647,
  0.4979706388752364,
  0.17808996305717795,
  0.32123566339024767,
  0.08104290335121433],
 [0.08876106728473176,
  0.891590904341702,
  0.06140141835125579,
  0.7829936953146214,
  0.5608423069

**2**

In [26]:
rowSum = [sum(x) for x in matrix]
columnSum = [sum(x) for x in zip(*matrix)]
print(f'Row sum = {rowSum}')
print(f'Column sum = {columnSum}')

Row sum = [3.9948115978092353, 5.0042793423240415, 5.783364197331835, 2.665649191642705, 4.139888070546088, 5.907409292583126, 5.546541921041264, 4.199174653520134, 4.820283258649251, 5.7259015440599885]
Column sum = [5.17537933759602, 6.165730212677174, 5.158662076054983, 3.7866367105837266, 4.545688989648429, 6.079617766821205, 4.630351531461103, 3.436472543143417, 4.224995505682959, 4.5837683958386535]


### 3

**1**

In [27]:
import numpy

heights = numpy.array([140, 200, 175, 120, 150], numpy.float64)
heights

array([140., 200., 175., 120., 150.])

**2**

In [28]:
widths = numpy.array([7, 10, 15, 8, 12], numpy.float64)
widths

array([ 7., 10., 15.,  8., 12.])

**3**

In [29]:
areas = heights * widths
areas

array([ 980., 2000., 2625.,  960., 1800.])

**4**

In [30]:
indices = numpy.arange(0, len(heights), dtype=numpy.int64)
indices

array([0, 1, 2, 3, 4], dtype=int64)

**5**

In [31]:
plant_info = numpy.transpose(numpy.array([indices, heights, widths]))
plant_info

array([[  0., 140.,   7.],
       [  1., 200.,  10.],
       [  2., 175.,  15.],
       [  3., 120.,   8.],
       [  4., 150.,  12.]])

**6**

In [32]:
identity_matrix = numpy.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**7**

**8**