# Seyed Mohammad Amin Atyabi - 830402014

## NumPy

### 1

**1**

In [51]:
import random

vector = [random.randint(10, 1000) for x in range(0, 1000)]
print(f'Length = {len(vector)}')
print(f'Vector = {vector}')

Length = 1000
Vector = [713, 875, 622, 435, 714, 489, 921, 725, 448, 160, 764, 981, 111, 344, 849, 554, 508, 340, 766, 515, 528, 542, 985, 580, 411, 974, 787, 894, 462, 310, 606, 768, 311, 847, 160, 269, 596, 903, 661, 709, 996, 674, 321, 305, 183, 626, 85, 871, 259, 574, 266, 139, 588, 143, 532, 766, 259, 492, 655, 114, 217, 843, 645, 827, 963, 33, 471, 768, 270, 531, 760, 768, 178, 340, 409, 590, 208, 999, 582, 181, 236, 814, 818, 741, 124, 808, 362, 514, 363, 48, 872, 589, 45, 452, 490, 370, 168, 828, 297, 858, 174, 568, 350, 529, 23, 825, 347, 796, 395, 421, 798, 897, 344, 997, 550, 505, 894, 143, 50, 905, 447, 974, 130, 766, 979, 848, 795, 828, 487, 866, 443, 197, 286, 736, 230, 370, 359, 889, 580, 544, 698, 426, 183, 123, 262, 128, 46, 610, 279, 995, 167, 81, 690, 586, 898, 618, 715, 301, 592, 238, 978, 587, 68, 838, 583, 892, 941, 512, 730, 899, 218, 645, 283, 129, 670, 475, 727, 280, 804, 425, 901, 971, 452, 91, 980, 78, 599, 248, 140, 999, 562, 706, 757, 738, 751, 459, 94, 589

**2**

In [52]:
_sum_ = sum(vector)
count = len(vector)
mean = _sum_ / count
variance = (sum(map(lambda x: (x - mean) ** 2, vector))) / (count - 1)
print(f'Average = {mean}')
print(f'Variance = {variance}')

Average = 508.481
Variance = 83390.43006906901


### 2

**1**

In [53]:
matrix = [[random.random() for j in range(0, 10)] for i in range(0, 10)]
print(matrix)

[[0.7185843957182134, 0.6211447354118991, 0.3518500154787654, 0.21628321748596768, 0.9011818020516452, 0.11929566135401526, 0.17800094946235112, 0.47442684556803605, 0.9821502477068735, 0.5145313182757357], [0.6358797665879684, 0.37800977802092184, 0.7059652736511501, 0.44625054611229087, 0.3254907376455646, 0.13928250639486983, 0.05798144025314411, 0.5557556742942343, 0.20392866734091775, 0.18731009564500667], [0.7112306105575263, 0.7222000364309338, 0.7200418516911162, 0.5474397925692841, 0.9737667182083322, 0.4591458894390609, 0.19125028294639912, 0.946915693661029, 0.453315556688183, 0.36536597259028436], [0.7410331339271998, 0.19846485677155357, 0.6024017052350379, 0.6137170306472799, 0.22566094876610354, 0.30228632602384564, 0.8666945162976792, 0.37193914212947765, 0.8680374478723141, 0.5374261306965412], [0.9576663387273732, 0.39341720354167564, 0.12315469809337753, 0.029630094685068498, 0.33932272954590503, 0.9747441419700166, 0.7927690168521025, 0.9575812162116657, 0.016446046

**2**

In [54]:
rowSum = [sum(x) for x in matrix]
columnSum = [sum(x) for x in zip(*matrix)]
print(f'Row sum = {rowSum}')
print(f'Column sum = {columnSum}')

Row sum = [5.077449188513502, 3.6358544859460684, 6.090672404782149, 5.327661238367033, 4.61778582960003, 6.429109781107052, 4.837861777098607, 4.838237639328313, 4.835579278134672, 4.109250698695674]
Column sum = [5.971479733872026, 5.642185881737589, 4.838710381645768, 5.378950904511141, 5.0974899010164725, 4.004249347172375, 3.8967422148742417, 5.975917780596124, 4.4219908945863375, 4.571745281561027]


### 3

**1**

In [55]:
import numpy

heights = numpy.array([140, 200, 175, 120, 150], numpy.float64)
print(f'Heights = {heights}')
print(f'Type = {heights.dtype}')

Heights = [140. 200. 175. 120. 150.]
Type = float64


**2**

In [56]:
widths = numpy.array([7, 10, 15, 8, 12], numpy.float64)
print(f'Widths = {widths}')
print(f'Type = {widths.dtype}')

Widths = [ 7. 10. 15.  8. 12.]
Type = float64


**3**

In [57]:
areas = heights * widths
print(f'Areas = {areas}')

Areas = [ 980. 2000. 2625.  960. 1800.]


**4**

In [58]:
indices = numpy.arange(0, len(heights), dtype=numpy.int64)
print(f'Indices = {indices}')

Indices = [0 1 2 3 4]


**5**

In [59]:
plant_info = numpy.transpose(numpy.array([indices, heights, widths]))
print(plant_info)

[[  0. 140.   7.]
 [  1. 200.  10.]
 [  2. 175.  15.]
 [  3. 120.   8.]
 [  4. 150.  12.]]


**6**

In [60]:
identity_matrix = numpy.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**7**

In [61]:
diagonal_matrix = numpy.diag(areas)
print(diagonal_matrix)

[[ 980.    0.    0.    0.    0.]
 [   0. 2000.    0.    0.    0.]
 [   0.    0. 2625.    0.    0.]
 [   0.    0.    0.  960.    0.]
 [   0.    0.    0.    0. 1800.]]


**8**

In [62]:
squared_sums = numpy.fromfunction(lambda i, j: sum(plant_info ** 2), (1, 4), dtype=int).astype(int)
print(squared_sums)

[    30 127125    582]


### 4

**1**

In [63]:
treasure_map = numpy.random.randint(1, 7, size=(4, 5))
print(treasure_map)
print(f'Type = {treasure_map.dtype}')
print(f'Shape = {treasure_map.shape}')
print(f'Size = {treasure_map.size}')
print(f'length = {len(treasure_map)}')

[[4 5 1 2 2]
 [1 2 3 6 2]
 [2 2 6 4 1]
 [1 5 1 2 1]]
Type = int32
Shape = (4, 5)
Size = 20
length = 4


**2**

In [64]:
reshaped_treasure_map = numpy.reshape(treasure_map, (2, -1))
print(reshaped_treasure_map)

[[4 5 1 2 2 1 2 3 6 2]
 [2 2 6 4 1 1 5 1 2 1]]


**3**

In [65]:
print(f'Original = {treasure_map[0]}')
print(f'Reshaped = {reshaped_treasure_map[0]}')

Original = [4 5 1 2 2]
Reshaped = [4 5 1 2 2 1 2 3 6 2]


**4**

In [66]:
print(f'Original = {treasure_map[:, 0]}')
print(f'Reshaped = {reshaped_treasure_map[:, 0]}')

Original = [4 1 2 1]
Reshaped = [4 2]


**5**

In [67]:
print(f'Original = {treasure_map[-1]}')
print(f'Reshaped = {reshaped_treasure_map[-1]}')

Original = [1 5 1 2 1]
Reshaped = [2 2 6 4 1 1 5 1 2 1]


**6**

In [68]:
print(f'Original = {treasure_map[1][1]}')
print(f'Reshaped = {reshaped_treasure_map[1][1]}')

Original = 2
Reshaped = 2


**7**

In [69]:
print(treasure_map[:, 1:4])

[[5 1 2]
 [2 3 6]
 [2 6 4]
 [5 1 2]]


**8**

In [88]:
map_mask = treasure_map <= 2
print(map_mask)

[[False False  True  True  True]
 [ True  True False False  True]
 [ True  True False False  True]
 [ True False  True  True  True]]


**9**

In [96]:
print(numpy.reshape(numpy.where(map_mask==True), (-1, 2)))

[[0 0]
 [0 1]
 [1 1]
 [2 2]
 [2 3]
 [3 3]
 [3 2]
 [3 4]
 [0 1]
 [4 0]
 [1 4]
 [0 2]
 [3 4]]


**10**

In [97]:
print(f'(0, 1) = {treasure_map[0][1]}')
print(f'(0, 2) = {treasure_map[0][2]}')

(0, 1) = 5
(0, 2) = 1
