# Seyed Mohammad Amin Atyabi - 830402014

## NumPy

### 1

**1**

In [97]:
import random

vector = [random.randint(10, 1000) for x in range(0, 1000)]
print(f'Length = {len(vector)}')
print(f'Vector = {vector}')

Length = 1000
Vector = [75, 246, 516, 732, 658, 578, 912, 485, 577, 683, 230, 277, 344, 636, 894, 81, 97, 420, 42, 869, 655, 631, 685, 547, 241, 719, 546, 125, 862, 777, 42, 217, 646, 485, 706, 859, 698, 621, 618, 584, 730, 425, 737, 316, 313, 908, 561, 472, 159, 984, 711, 771, 485, 152, 478, 749, 556, 381, 242, 52, 29, 809, 763, 687, 670, 513, 13, 888, 258, 888, 447, 79, 81, 989, 352, 398, 54, 199, 583, 984, 910, 479, 595, 223, 80, 871, 530, 60, 973, 530, 717, 441, 652, 30, 325, 536, 401, 431, 530, 666, 511, 896, 570, 244, 328, 93, 1000, 915, 429, 233, 192, 369, 821, 416, 291, 459, 771, 951, 616, 336, 753, 637, 151, 317, 563, 848, 820, 930, 902, 355, 23, 462, 654, 83, 279, 370, 780, 249, 573, 718, 938, 108, 741, 203, 406, 598, 641, 583, 909, 772, 173, 374, 23, 102, 715, 102, 881, 948, 141, 76, 795, 677, 137, 373, 942, 477, 501, 903, 575, 235, 806, 114, 384, 805, 559, 475, 821, 488, 521, 264, 298, 318, 135, 915, 278, 264, 240, 288, 398, 471, 361, 881, 669, 785, 627, 726, 366, 162, 842,

**2**

In [98]:
_sum_ = sum(vector)
count = len(vector)
mean = _sum_ / count
variance = (sum(map(lambda x: (x - mean) ** 2, vector))) / (count - 1)
print(f'Average = {mean}')
print(f'Variance = {variance}')

Average = 493.892
Variance = 82527.21955555561


### 2

**1**

In [99]:
matrix = [[random.random() for j in range(0, 10)] for i in range(0, 10)]
print(matrix)

[[0.3994969322455433, 0.65485596364702, 0.4862893171586047, 0.7962006576297705, 0.9674398417632719, 0.8740730135925999, 0.5636728151827004, 0.2185118101247424, 0.8623525308635901, 0.2922137044882964], [0.33061940448074456, 0.538220996719911, 0.5592580760976626, 0.5162579993995826, 0.13006564179215419, 0.8867745849218428, 0.9240621217235309, 0.5907647061131825, 0.18467744308176604, 0.2716319359536743], [0.07635453826984029, 0.8069129151272674, 0.4289245161376124, 0.14683700745735506, 0.9641127499962554, 0.28977392409357317, 0.054824609330571206, 0.8273282606685785, 0.4025614118340147, 0.988378511275604], [0.8212633191072638, 0.43083883353604246, 0.7702231856870138, 0.2825598478693965, 0.898605210123922, 0.07383857817039041, 0.796587951008467, 0.4398966089391684, 0.48169698858827914, 0.8905548871894304], [0.45412723532733845, 0.9193945057645346, 0.8045550441872946, 0.33588265632385617, 0.7396359399050015, 0.6574718077691002, 0.290936882869576, 0.9406994703067457, 0.8409949503284211, 0.78

**2**

In [100]:
rowSum = [sum(x) for x in matrix]
columnSum = [sum(x) for x in zip(*matrix)]
print(f'Row sum = {rowSum}')
print(f'Column sum = {columnSum}')

Row sum = [6.1151065866961405, 4.932332910284051, 4.986008444190672, 5.886065410219374, 6.77221095321015, 5.884952911662836, 4.848092273288174, 6.015430070030856, 3.9060910624984464, 5.484108674973079]
Column sum = [5.896737925440697, 6.43336708713515, 5.46632041603084, 3.96782300082176, 6.223328064898182, 4.648170609531111, 5.261068202703668, 5.848650383789759, 6.263969330440252, 4.820964276262354]


### 3

**1**

In [101]:
import numpy

heights = numpy.array([140, 200, 175, 120, 150], numpy.float64)
print(f'Heights = {heights}')
print(f'Type = {heights.dtype}')

Heights = [140. 200. 175. 120. 150.]
Type = float64


**2**

In [102]:
widths = numpy.array([7, 10, 15, 8, 12], numpy.float64)
print(f'Widths = {widths}')
print(f'Type = {widths.dtype}')

Widths = [ 7. 10. 15.  8. 12.]
Type = float64


**3**

In [103]:
areas = heights * widths
print(f'Areas = {areas}')

Areas = [ 980. 2000. 2625.  960. 1800.]


**4**

In [104]:
indices = numpy.arange(0, len(heights), dtype=numpy.int64)
print(f'Indices = {indices}')

Indices = [0 1 2 3 4]


**5**

In [105]:
plant_info = numpy.transpose(numpy.array([indices, heights, widths]))
print(plant_info)

[[  0. 140.   7.]
 [  1. 200.  10.]
 [  2. 175.  15.]
 [  3. 120.   8.]
 [  4. 150.  12.]]


**6**

In [106]:
identity_matrix = numpy.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**7**

In [107]:
diagonal_matrix = numpy.diag(areas)
print(diagonal_matrix)

[[ 980.    0.    0.    0.    0.]
 [   0. 2000.    0.    0.    0.]
 [   0.    0. 2625.    0.    0.]
 [   0.    0.    0.  960.    0.]
 [   0.    0.    0.    0. 1800.]]


**8**

In [108]:
squared_sums = numpy.fromfunction(lambda i, j: sum(plant_info ** 2), (1, 4), dtype=int).astype(int)
print(squared_sums)

[    30 127125    582]
